name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install nasm
      run: sudo apt install nasm
    - name: default debug
      run: |
        make fclean test CC=cc
    - name: gcc debug
      run: |
        make fclean test CC=gcc
    - name: clang debug
      run: |
        make fclean test CC=clang
    - name: default release
      run: |
        make fclean test BUILD=release CC=cc
    - name: gcc release
      run: |
        make fclean test BUILD=release CC=gcc
    - name: clang release
      run: |
        make fclean test BUILD=release CC=clang
    - name: default normal
      run: |
        make fclean test BUILD=normal CC=cc
    - name: gcc normal
      run: |
        make fclean test BUILD=normal CC=gcc
    - name: clang normal
      run: |
        make fclean test BUILD=normal CC=clang
